### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by Awoolen** [nhscc/barker.api.hscc.bdpa.org#15]
I would like to request an API key for the Washington DC team.

**Comment by Xunnamius** [comment]
Keys will go out this weekend over BDPA Slack. If your chapter still hasn't gotten a key by Sunday, reply back here or DM me on Slack

**Comment by Awoolen** [comment]
Thanks 
 
  On Sat, Jun 5, 2021 at 6:19 AM, ***@***.***> wrote:   


Keys will go out this weekend over BDPA Slack. If your chapter still hasn't gotten a key by Sunday, reply back here or DM me on Slack

**Comment by Xunnamius** [comment]
@Awoolen Closing this for now. API keys are going out over Slack. Please request one through the official channel, thanks!
